[project]
name = "repl-nix-sentimentanalyzericl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.1.0",
    "fpdf>=1.7.2",
    "openai>=1.55.1",
    "pandas>=2.2.3",
    "streamlit>=1.40.2",
]
