[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false
