[server]
headless = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
